title: O știi p-aia cu?
baseurl: /ostiipaiacu.ro
url: https://revolter.github.io

remote_theme: jekyll/minima
plugins:
    - jekyll-feed
    - jekyll-octicons
    - jekyll-remote-theme
minima:
    skin: auto
    date_format: "%F"
kramdown:
    smart_quotes: apos,apos,quot,quot
exclude:
    - .jekyll-cache/
    - .sass-cache/
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
    - package-lock.json
    - package.json
    - README.md
