title: O știi p-aia cu?
url: https://ostiipaiacu.ro

# Disabled due to https://github.com/rubygems/rubygems/issues/7652
# theme: minima
# Added due to https://github.com/rubygems/rubygems/issues/7652
remote_theme: jekyll/minima
plugins:
    - jekyll-feed
    - jekyll-octicons
    # Added due to https://github.com/rubygems/rubygems/issues/7652
    - jekyll-remote-theme
exclude:
    - LICENSE.md
    - package-lock.json
    - package.json
    - README.md
defaults:
    - scope:
          path: ""
      values:
          image: /assets/images/favicon/android-chrome-512x512.png
    - scope:
          path: ''
          type: posts
      values:
          layout: custom-post

feed:
    path: /feeds/feed.xml
    tags:
        path: /feeds/
        only:
            - SFW
            - NSFW
kramdown:
    smart_quotes: apos,apos,quot,quot
minima:
    skin: auto
    date_format: "%F"
    social_links:
        - platform: github
          user_url: https://github.com/revolter/ostiipaiacu.ro
sass:
    style: compressed
    sourcemap: development
