title: O știi p-aia cu?
email: your-email@example.com
description: >-
    Write an awesome description for your new site here. You can edit this
    line in _config.yml. It will appear in your document head meta (for
    Google search results) and in your feed.xml site description.
baseurl: /ostiipaiacu.ro
url: https://revolter.github.io
twitter_username: jekyllrb
github_username:  jekyll

remote_theme: jekyll/minima
plugins:
    - jekyll-feed
    - jekyll-octicons
    - jekyll-remote-theme
minima:
    skin: auto
    date_format: "%F"
kramdown:
    smart_quotes: apos,apos,quot,quot
exclude:
    - .jekyll-cache/
    - .sass-cache/
    - node_modules/
    - vendor/bundle/
    - vendor/cache/
    - vendor/gems/
    - vendor/ruby/
    - Gemfile
    - Gemfile.lock
    - package-lock.json
    - package.json
    - README.md
