title: O știi p-aia cu?
baseurl: /ostiipaiacu.ro
url: https://revolter.github.io

remote_theme: jekyll/minima
plugins:
    - jekyll-feed
    - jekyll-octicons
    - jekyll-remote-theme
exclude:
    - LICENSE.md
    - package-lock.json
    - package.json
    - README.md

feed:
    path: /feeds/feed.xml
    tags:
        path: /feeds/
        only:
            - SFW
            - NSFW
kramdown:
    smart_quotes: apos,apos,quot,quot
minima:
    skin: auto
    date_format: "%F"
    social_links:
        - platform: github
          user_url: https://github.com/revolter/ostiipaiacu.ro
