name: Preview Jekyll site with GitHub Pages

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
      - closed

concurrency: preview-${{ github.ref }}

jobs:
  preview:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.3
          bundler-cache: true
          cache-version: 0
      - name: Build with Jekyll
        if: github.event.action != 'closed'
        run: bundle exec jekyll build --verbose --trace --baseurl '${{ steps.pages.outputs.base_path }}'
        env:
          JEKYLL_ENV: production
      - name: Deploy preview
        uses: rossjrw/pr-preview-action@v1
        with:
          source-dir: ./_site/
